config/routes.rb
Foursq::Application.routes.draw do
  get "api/ping", :defaults => { :format => :json }
  get "foursquare/connect"
  get "foursquare/callback"

  root :to => "devices#index"

  resources :devices
  devise_for :users

end

app/models/device.rb
class Device < ActiveRecord::Base
  include ActiveModel::Validations

  validates_presence_of :name
  validates_presence_of :mac_address

  belongs_to :user
  has_many :entries

  def seen_today?(today=nil)
    today = DateTime.now if today.nil?

    limit_start = DateTime.new(today.year, today.month, today.day)
    limit_end   = DateTime.new(today.year, today.month, today.day, 23, 59, 59)

    entries.where(:created_at => limit_start..limit_end).count > 0
  end

  def mac_address=(address)
    if not address.nil?
      address.upcase!
    end

    self[:mac_address] = address
  end
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  include ActiveModel::Validations

  validates_presence_of :device_id

  belongs_to :device
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :devices, :dependent => :destroy

  def foursquare_client
    Foursquare2::Client.new(:oauth_token => foursquare_token, :api_version => '20140312')
  end

  def seen_today?(today=nil)
    devices.each do |device|
      return true if device.seen_today?(today)
    end

    return false
  end

  def checkin(venue_id)
    venue = foursquare_client.venue(venue_id)
    venue_lat_lon = "%.5f,%.5f" % [venue.location.lat, venue.location.lng]

    foursquare_client.add_checkin(
      :venueId => venue_id,
      :broadcast => 'public',
      :shout => "Automatic check-in.",
      :ll => venue_lat_lon,
      :llAcc => 1,
      :alt => 0,
      :altAcc => 1
    )
  end
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  def ping
    response = {}

    mac_addresses = (params[:mac_addresses].upcase || "").split ","
    devices = Device.where('mac_address IN (?)', mac_addresses)

    total_devices_found = 0
    total_users_checked_in = 0

    devices.each do |device|
      total_devices_found = total_devices_found + 1

      unless device.user.seen_today?
        total_users_checked_in = total_users_checked_in + 1

        device.user.checkin ENV['FOURSQUARE_VENUE_ID']
        device.entries << Entry.create(
          :created_at => DateTime.now
        )
      end
    end

    response[:total_devices] = total_devices_found
    response[:total_checked_in] = total_users_checked_in

    respond_to do |format|
      format.json { render :json => response }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_device, only: [:show, :edit, :update, :destroy]

  # GET /devices
  # GET /devices.json
  def index
    @devices = current_user.devices
  end

  # GET /devices/1
  # GET /devices/1.json
  def show
  end

  # GET /devices/new
  def new
    @device = Device.new
  end

  # GET /devices/1/edit
  def edit
  end

  # POST /devices
  # POST /devices.json
  def create
    @device = Device.new(device_params)

    respond_to do |format|
      if @device.save
        format.html { redirect_to @device, notice: 'Device was successfully created.' }
        format.json { render action: 'show', status: :created, location: @device }
      else
        format.html { render action: 'new' }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /devices/1
  # PATCH/PUT /devices/1.json
  def update
    respond_to do |format|
      if @device.update(device_params)
        format.html { redirect_to @device, notice: 'Device was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devices/1
  # DELETE /devices/1.json
  def destroy
    @device.destroy
    respond_to do |format|
      format.html { redirect_to devices_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_device
      @device = current_user.devices.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def device_params
      clean_params = params.require(:device).permit(:name, :mac_address)
      clean_params[:user] = current_user

      return clean_params
    end
end

app/controllers/foursquare_controller.rb
class FoursquareController < ApplicationController
  protect_from_forgery :except => :callback
  before_filter :authenticate_user!

  def initialize
    app_id = ENV['FOURSQUARE_APP_ID']
    app_secret = ENV['FOURSQUARE_APP_SECRET']

    @foursquare = OAuth2::Client.new(
      app_id,
      app_secret,
      :authorize_url => "/oauth2/authorize",
      :token_url => "/oauth2/access_token",
      :site => "https://foursquare.com/"
    )
  end

  def connect
    redirect_to @foursquare.auth_code.authorize_url(:redirect_uri => foursquare_callback_url)
  end

  def callback
    code = params[:code]
    token = @foursquare.auth_code.get_token(code, :redirect_uri => foursquare_callback_url)

    current_user.update(:foursquare_token => token.token)

    redirect_to root_path
  end
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/helpers/foursquare_helper.rb
module FoursquareHelper
end

app/views/devices/_form.html.erb
<%= form_for(@device) do |f| %>
  <% if @device.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@device.errors.count, "error") %> prohibited this device from being saved:</h2>

      <ul>
      <% @device.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :mac_address %><br>
    <%= f.text_field :mac_address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/devices/edit.html.erb
<h1>Editing device</h1>

<%= render 'form' %>

<%= link_to 'Show', @device %> |
<%= link_to 'Back', devices_path %>

app/views/devices/index.html.erb
<h1>Listing devices</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Mac address</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @devices.each do |device| %>
      <tr>
        <td><%= device.name %></td>
        <td><%= device.mac_address %></td>
        <td><%= link_to 'Show', device %></td>
        <td><%= link_to 'Edit', edit_device_path(device) %></td>
        <td><%= link_to 'Destroy', device, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Device', new_device_path %>

app/views/devices/new.html.erb
<h1>New device</h1>

<%= render 'form' %>

<%= link_to 'Back', devices_path %>

app/views/devices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @device.name %>
</p>

<p>
  <strong>Mac address:</strong>
  <%= @device.mac_address %>
</p>

<%= link_to 'Edit', edit_device_path(@device) %> |
<%= link_to 'Back', devices_path %>

app/views/foursquare/callback.html.erb
<h1>Foursquare#callback</h1>
<p>Find me in app/views/foursquare/callback.html.erb</p>

app/views/foursquare/connect.html.erb
<h1>Foursquare#connect</h1>
<p>Find me in app/views/foursquare/connect.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Foursq</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if user_signed_in? %>
  <p>Welcome <%= current_user.email %></p>
  <%= link_to 'Logged In [click to logout]', destroy_user_session_path, :method => :delete %>
  <% unless current_user.foursquare_token %>
    <%= link_to 'Connect with Foursquare', foursquare_connect_path %>.
  <% end %>
<% else %>
  <p>You are not signed in.</p>
  <%= link_to 'Login', new_user_session_path %>
<% end %>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>